### ISSUE TITLE
v0.2.x Checklist

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/commandlines#1]
### TODO
- [X] Multiple options in any order.
- [X] Short switch syntax (e.g. `-s`)
- [X] Long switch syntax (e.g. `--long`) 
- [X] Alternate long switch syntax (e.g. `-name`)
- [X] Short option argument definition syntax (e.g. `-s path`)
- [X] Long option argument definition syntax (e.g. `--long path`)
- [X] Alternate long option argument definition syntax (e.g. `--long=path`)
- [X] Multiple option short switch syntax (e.g. `-mops`)
- [x] methods to support command logic in source code
