### ISSUE TITLE
v0.3.x checklist

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/commandlines#2]
- [x] Support for the `--` command line token (e.g. `touch -- -stupid-filename`) 
- [x] Support for multiple same option definitions (e.g. `-o <path1> -o <path2>`)
- [x] Implement mandatory argument test that supports short / long option alternatives
